
#************************************************
#SUPABASE DATABASE
#************************************************
# Data source configuration
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.yajgmjyhrbgailbygriw
spring.datasource.password=caterpie2024
# JPA/Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


#************************************************
#GOOGLE DATABASE
#************************************************
# Data source configuration
#spring.datasource.url=jdbc:postgresql://34.132.10.15:5432/bar_website
#spring.datasource.username=caterpie
#spring.datasource.password=caterpie
# JPA/Hibernate settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


#***************************************************
#LOCAL BACKUP DATABASE:
#***************************************************
# Data source configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/bar_website
#spring.datasource.username=caterpie
#spring.datasource.password=caterpie
# JPA/Hibernate settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true